- name: Update apt cache if not done so recently
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install requirements for docker ce
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg-agent 
    - software-properties-common

- name: add key
  apt_key:
    url: "{{ docker_gpg_key_url }}"

- name: add repo
  apt_repository:
    repo: "deb {{ docker_repo_base_url }} /"
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
