gpg_key_url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
              
kubernetes_sources_file: "/etc/apt/sources.list.d/kubernetes.list"

apt_kube_key: "deb https://apt.kubernetes.io/ kubernetes-xenial main"