pod_network: --pod-network-cidr=10.244.0.0/16

kube_file_path: "/home/kube_master/.kube"
kube_config_path: "/home/kube_master/.kube/config"


kube_admin_file: "/etc/kubernetes/admin.conf"

flannel_url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
nvidia_device_plugin: "https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta3/nvidia-device-plugin.yml"