---
- hosts: gpu_workstations
  user: root
  become: yes
  tasks:
  - debug:
      msg: "Installing nvidia docker ..."
  - import_role:
      name: nvidia_docker
  - debug:
      msg: "Nvidia Docker install finished!"